### ISSUE TITLE
text status updates

### ISSUE THREAD

**Issue by nsheff** [databio/shinyLOLA#3]
The new text updates are working great, but there are a few issues:

- "Calculating Fisher scores..." remains after job is complete.
- notices now appear in 2 locations: top right ("calculating region set enrichments..." and under the green button. let's consolidate
- notices are too long and go off the screen if on narrow screens
- should we move the runLOLA button? it seems strange hanging out over on the right side away from everything else.

**Comment by vpnagraj** [comment]
reworked the notification messages in 22e8c62 and 3e808ee ... pretty sure that resolves these issues
