### ISSUE TITLE
default cutoffs

### ISSUE THREAD

**Issue by nsheff** [databio/shinyLOLA#4]
Right now the default cutoffs are set such that there are no hits present in any plots.

Can we work out a way to get a reasonable cutoffs such that there will be a few hits present by default? Maybe, 25 hits or something?

Suggestion: take the `.25` quantile as the default for both odds ratio and support; and then just rank and take set the p-value cutoff to score on number 25. then we're guaranteed to show exactly 25 by default. in other words, 2 should be loose, hard-coded default cutoffs, and the other should be a dynamic based on number of items.

**Comment by vpnagraj** [comment]
this should be resolved with the max rank slider in 43e34c2
